### PR TITLE
Check if processCompartmentId is null

### PR DESCRIPTION
**Pull request by tczauderna**

### CODE REVIEW

**Comment by cannin** [comment]
@tczauderna Can you increment the version in the pom.xml to 0.4.6? To make it easier for everyone to know what the latest version is.

**Comment by tczauderna** [comment]
Done

**Comment by ugurdogrusoz** [comment]
@msalihaltun Please update our service for this and try it in Newt and merge if all is fine.

**Review by msalihaltun — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
